

mahalleler[] = [
    { townValue: 'adalar', townDisplay: 'Adalar', value: 'burgazada', display: 'Burgazada' },
    { townValue: 'adalar', townDisplay: 'Adalar', value: 'buyukada', display: 'Büyükada' },
    { townValue: 'adalar', townDisplay: 'Adalar', value: 'heybeliada', display: 'Heybeliada' },
    { townValue: 'adalar', townDisplay: 'Adalar', value: 'kinaliada', display: 'Kınalıada' },
    { townValue: 'adalar', townDisplay: 'Adalar', value: 'maden', display: 'Maden' },
    { townValue: 'adalar', townDisplay: 'Adalar', value: 'nizam', display: 'Nizam' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'anadolu', display: 'Anadolu' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'imrahor', display: 'İmrahor' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'islambey', display: 'İslambey' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'merkez', display: 'Merkez' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'ataturk', display: 'Atatürk' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'bolluca_merkez', display: 'Bolluca' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'deliklikaya', display: 'Deliklikaya' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'durusu_cami', display: 'Durusu' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'hadimkoy', display: 'Hadımköy' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'imrahor', display: 'İmrahor' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'i̇slambey', display: 'İslambey' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'karaburun', display: 'Karaburun' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'mavigol', display: 'Mavigöl' }, ,
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'mustafa_kemal_pasa', display: 'Mustafa Kemal Paşa' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'omerli', display: 'Ömerli' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'tasoluk', display: 'Taşoluk' },
    { townValue: 'arnavutkoy', townDisplay: 'Arnavutköy', value: 'yenikoy', display: 'Yenikoy' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'asikveysel', display: 'Aşıkveysel' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'ataturk', display: 'Atatürk' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'barbaros', display: 'Barbaros' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'esatpasa', display: 'Esatpaşa' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'ferhatpasa', display: 'Ferhatpaşa' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'fetih', display: 'Fetih' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'i̇cerenkoy', display: 'İçerenköy' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'i̇nonu', display: 'İnönü' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'kayisdagi', display: 'Kayışdağı' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'kucukbakkalkoy', display: 'Küçükbakkalköy' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'mevlana', display: 'Mevlana' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'mimarsinan', display: 'Mimarsinan' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'mustafa_kemal', display: 'Mustafa Kemal' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'ornek', display: 'Örnek' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'yenicamlica', display: 'Yeniçamlıca' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'yenisehir', display: 'Yenişehir' },
    { townValue: 'atasehir', townDisplay: 'Ataşehir', value: 'yenisahra', display: 'Yenisahra' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'ambarli', display: 'Ambarlı' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'cihangir', display: 'Cihangir' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'denizkoskler', display: 'Denizköşkler' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'firuzkoy', display: 'Firuzköy' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'gumuspala', display: 'Gümüşpala' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'merkez', display: 'Merkez' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'mustafa_kemal_pasa', display: 'Mustafa Kemal Paşa' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'tahtakale', display: 'Tahtakale' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'universite', display: 'Üniversite' },
    { townValue: 'avcilar', townDisplay: 'Avcılar', value: 'yesilkent', display: 'Yeşilkent' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'baglar', display: 'Bağlar' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'barbaros', display: 'Barbaros' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'cinar', display: 'Çınar' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'demirkapi', display: 'Demirkapı' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'evren', display: 'Evren' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'fatih', display: 'Fatih' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'fevzi_cakmak', display: 'Fevzi Çakmak' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'goztepe', display: 'Göztepe' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'gunesli', display: 'Güneşli' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'hurriyet', display: 'Hürriyet' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'i̇nonu', display: 'İnönü' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'kazim_karabekir', display: 'Kazım Karabekir' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'kemalpasa', display: 'Kemalpaşa' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'kirazli', display: 'Kirazlı' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'mahmutbey', display: 'Mahmutbey' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'merkez', display: 'Merkez' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'sancaktepe', display: 'Sancaktepe' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'yavuzselim', display: 'Yavuzselim' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'yenigun', display: 'Yenigün' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'yildiztepe', display: 'Yıldıztepe' },
    { townValue: 'bagcilar', townDisplay: 'Bağcılar', value: 'yuzyil', display: 'Yüzyıl' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'bahcelievler', display: 'Bahçelievler' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'cobancesme', display: 'Çobançeşme' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'fevzi_cakmak', display: 'Fevzi Çakmak' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'hurriyet', display: 'Hürriyet' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'kocasinan', display: 'Kocasinan' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'siyavuspasa', display: 'Siyavuşpaşa' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'soganli', display: 'Soğanlı' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'sirinevler', display: 'Şirinevler' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'yenibosna', display: 'Yenibosna' },
    { townValue: 'bahcelievler', townDisplay: 'Bahçelievler', value: 'zafer', display: 'Zafer' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'atakoy_1_kisim', display: 'Ataköy 1. kısım' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'atakoy_2_5_6_kisim', display: 'Ataköy 2-5-6. kısım' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'atakoy_3_4_11_kisim', display: 'Ataköy 3-4-11. kısım' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'atakoy_7_8_9_10_kisim', display: 'Ataköy 7-8-9-10. kısım' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'basinkoy', display: 'Basınköy' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'cevizlik', display: 'Cevizlik' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'kartaltepe', display: 'Kartaltepe' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'osmaniye', display: 'Osmaniye' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'sakizagaci', display: 'Sakızağacı' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'senlikkoy', display: 'Şenlikköy' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'yesilkoy', display: 'Yeşilköy' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'yesilyurt', display: 'Yeşilyurt' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'zeytinlik', display: 'Zeytinlik' },
    { townValue: 'bakirkoy', townDisplay: 'Bakırköy', value: 'zuhuratbaba', display: 'Zuhuratbaba' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'altinsehir', display: 'Altınşehir' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'bahcesehir_1Kisim', display: 'Bahçeşehir 1.Kısım' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'bahcesehir_2Kisim', display: 'Bahçeşehir 2.Kısım' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'basak', display: 'Başak' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'basaksehir', display: 'Başakşehir' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'guvercintepe', display: 'Güvercintepe' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'kayabasi', display: 'Kayabaşı' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'sahintepe', display: 'Şahintepe' },
    { townValue: 'basaksehir', townDisplay: 'Başakşehir', value: 'ziya_gokalp', display: 'Ziya Gökalp' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'altintepsi', display: 'Altıntepsi' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'cevatpasa', display: 'Cevatpaşa' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'i̇smetpasa', display: 'İsmetpaşa' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'kartaltepe', display: 'Kartaltepe' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'kocatepe', display: 'Kocatepe' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'muratpasa', display: 'Muratpaşa' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'orta', display: 'Orta' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'terazidere', display: 'Terazidere' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'vatan', display: 'Vatan' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'yenidogan', display: 'Yenidoğan' },
    { townValue: 'bayrampasa', townDisplay: 'Bayrampaşa', value: 'yildirim', display: 'Yıldırım' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'abbasaga', display: 'Abbasağa' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'akatlar', display: 'Akatlar' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'arnavutkoy', display: 'Arnavutköy' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'balmumcu', display: 'Balmumcu' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'bebek', display: 'Bebek' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'cihannuma', display: 'Cihannüma' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'dikilitas', display: 'Dikilitaş' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'etiler', display: 'Etiler' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'gayrettepe', display: 'Gayrettepe' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'konaklar', display: 'Konaklar' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'kurucesme', display: 'Kuruçeşme' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'kultur', display: 'Kültür' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'levazim', display: 'Levazım' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'levent', display: 'Levent' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'mecidiye', display: 'Mecidiye' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'muradiye', display: 'Muradiye' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'nisbetiye', display: 'Nisbetiye' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'ortakoy', display: 'Ortaköy' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'sinanpasa', display: 'Sinanpaşa' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'turkali', display: 'Türkali' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'ulus', display: 'Ulus' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'visnezade', display: 'Vişnezade' },
    { townValue: 'besiktas', townDisplay: 'Beşiktaş', value: 'yildiz', display: 'Yıldız' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'acarlar', display: 'Acarlar' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'akbaba', display: 'Akbaba' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'anadoluhisari', display: 'Anadoluhisarı' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'anadolukavagi', display: 'Anadolukavağı' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'baklaci', display: 'Baklacı' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'camlibahce', display: 'Çamlıbahçe' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'cengeldere', display: 'Çengeldere' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'ciftlik', display: 'Çiftlik' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'cigdem', display: 'Çiğdem' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'cubuklu', display: 'Çubuklu' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'elmali', display: 'Elmalı' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'fatih', display: 'Fatih' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'goksu', display: 'Göksu' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'gorele', display: 'Görele' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'goztepe', display: 'Göztepe' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'gumussuyu', display: 'Gümüşsuyu' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'i̇ncirkoy', display: 'İncirköy' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'kanlica', display: 'Kanlıca' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'kavacik', display: 'Kavacık' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'mahmut_sevket_pasa', display: 'Mahmut Şevket Paşa' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'merkez', display: 'Merkez' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'ortacesme', display: 'Ortaçeşme' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'ogumce', display: 'Öğümce' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'pasabahce', display: 'Paşabahçe' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'pasamandira', display: 'Paşamandıra' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'polonezkoy', display: 'Polonezköy' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'riva', display: 'Riva' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'ruzgarlibahce', display: 'Rüzgarlıbahçe' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'soguksu', display: 'Soğuksu' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'tokatkoy', display: 'Tokatköy' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'yalikoy', display: 'Yalıköy' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'yavuz_selim', display: 'Yavuz Selim' },
    { townValue: 'beykoz', townDisplay: 'Beykoz', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'adnan_kahveci', display: 'Adnan Kahveci' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'baris', display: 'Barış' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'buyuksehir', display: 'Büyükşehir' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'dereagzi', display: 'Dereağzı' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'gurpinar', display: 'Gürpınar' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'kavakli', display: 'Kavaklı' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'marmara', display: 'Marmara' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'sahil', display: 'Sahil' },
    { townValue: 'beylikduzu', townDisplay: 'Beylikdüzü', value: 'yakuplu', display: 'Yakuplu' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'arapcami', display: 'Arapcami' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'asmalimescit', display: 'Asmalımescit' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'bedrettin', display: 'Bedrettin' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'bereketzade', display: 'Bereketzade' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'bostan', display: 'Bostan' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'bulbul', display: 'Bülbül' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'camiikebir', display: 'Camiikebir' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'cihangir', display: 'Cihangir' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'catmamescit', display: 'Çatmamescit' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'cukur', display: 'Çukur' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'emekyemez', display: 'Emekyemez' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'evliya_celebi', display: 'Evliya Çelebi' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'fetihtepe', display: 'Fetihtepe' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'firuzaga', display: 'Firuzağa' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'gumussuyu', display: 'Gümüşsuyu' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'haciahmet', display: 'Hacıahmet' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'hacimimi', display: 'Hacımimi' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'halicioglu', display: 'Halıcıoğlu' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'huseyinaga', display: 'Hüseyinağa' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'i̇stiklal', display: 'İstiklal' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kadi_mehmet_efendi', display: 'Kadı Mehmet Efendi' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kamerhatun', display: 'Kamerhatun' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kalyoncukullugu', display: 'Kalyoncukulluğu' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kaptanpasa', display: 'Kaptanpaşa' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'katip_mustafa_celebi', display: 'Katip Mustafa Çelebi' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kececipiri', display: 'Keçecipiri' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kemankes_kara_mustafa_pasa', display: 'Kemankeş Kara Mustafa Paşa' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kilicalipasa', display: 'Kılıçalipaşa' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kocatepe', display: 'Kocatepe' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kulaksiz', display: 'Kulaksız' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kuloglu', display: 'Kuloğlu' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'kucukpiyale', display: 'Küçükpiyale' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'mueyyetzade', display: 'Müeyyetzade' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'omeravni', display: 'Ömeravni' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'ornektepe', display: 'Örnektepe' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'piripasa', display: 'Piripaşa' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'piyalepasa', display: 'Piyalepaşa' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'purtelas', display: 'Pürtelaş' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'sururi', display: 'Sururi' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'sutluce', display: 'Sütlüce' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'sahkulu', display: 'Şahkulu' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'sehit_muhtar', display: 'Şehit Muhtar' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'tomtom', display: 'Tomtom' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'yahya_kahya', display: 'Yahya Kahya' },
    { townValue: 'beyoglu', townDisplay: 'Beyoğlu', value: 'yenisehir', display: 'Yenişehir' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: '19_mayis', display: '19 Mayıs' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'ahmediye', display: 'Ahmediye' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'alkent', display: 'Alkent' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'ataturk', display: 'Atatürk' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'bahcelievler', display: 'Bahçelievler' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'batikoy', display: 'Batıköy' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'celaliye', display: 'Celaliye' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'cakmakli', display: 'Çakmaklı' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'dizdariye', display: 'Dizdariye' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'fatih', display: 'Fatih' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'guzelce', display: 'Güzelce' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'hurriyet', display: 'Hürriyet' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'kamiloba', display: 'Kamiloba' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'karaagac', display: 'Karaağaç' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'mimaroba', display: 'Mimaroba' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'kumburgaz_merkez', display: 'Kumburgaz Merkez' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'mimarsinan', display: 'Mimarsinan' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'muratbey', display: 'Muratbey' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'muratcesme', display: 'Muratçeşme' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'pinartepe', display: 'Pınartepe' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'turkoba', display: 'Türkoba' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'ulus', display: 'Ulus' },
    { townValue: 'buyukcekmece', townDisplay: 'Büyükçekmece', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'binkilic', display: 'Binkılıç' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'cakil', display: 'Çakıl' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'ciftlikkoy', display: 'Çiftlikköy' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'fatih', display: 'Fatih' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'ferhatpasa', display: 'Ferhatpaşa' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'gokceali', display: 'Gökçeali' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'incegiz', display: 'İnceğiz' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'i̇zettin', display: 'İzettin' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'kaleici', display: 'Kaleiçi' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'kestanelik', display: 'Kestanelik' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'karacakoy', display: 'Karacaköy' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'ovayenice', display: 'Ovayenice' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'orcunlu', display: 'Örcünlü' },
    { townValue: 'catalca', townDisplay: 'Çatalca', value: 'subasi', display: 'Subaşı' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'alemdag', display: 'Alemdağ' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'aydinlar', display: 'Aydınlar' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'camlik', display: 'Çamlık' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'catalmese', display: 'Çatalmeşe' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'eksioglu', display: 'Ekşioğlu' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'gungoren', display: 'Güngören' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'hamidiye', display: 'Hamidiye' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'kirazlidere', display: 'Kirazlıdere' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'mehmet_akif', display: 'Mehmet Akif' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'merkez', display: 'Merkez' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'mimar_sinan', display: 'Mimar Sinan' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'nisantepe', display: 'Nişantepe' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'omerli', display: 'Ömerli' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'resadiye', display: 'Reşadiye' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'sirapinar', display: 'Sırapınar' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'sogukpinar', display: 'Soğukpınar' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'sultanciftligi', display: 'Sultançiftliği' },
    { townValue: 'cekmekoy', townDisplay: 'Çekmeköy', value: 'tasdelen', display: 'Taşdelen' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'esenler', display: 'Birlik' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'ciftehavuzlar', display: 'Çiftehavuzlar' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'davutpasa', display: 'Davutpaşa' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'fatih', display: 'Fatih' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'fevzi_cakmak', display: 'Fevzi Çakmak' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'havaalani', display: 'Havaalanı' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'kazim_karabekir', display: 'Kazım Karabekir' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'kemer', display: 'Kemer' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'menderes', display: 'Menderes' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'mimarsinan', display: 'Mimarsinan' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'namik_kemal', display: 'Namık Kemal' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'nenehatun', display: 'Nenehatun' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'orucreis', display: 'Oruçreis' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'tuna', display: 'Tuna' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'turgutreis', display: 'Turgutreis' },
    { townValue: 'esenler', townDisplay: 'Esenler', value: 'yavuz_selim', display: 'Yavuz Selim' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'akcaburgaz', display: 'Akçaburgaz' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'ardiclievler', display: 'Ardıçlıevler' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'ataturk', display: 'Atatürk' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'cakmakli', display: 'Çakmaklı' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'esenkent', display: 'Esenkent' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'fatih', display: 'Fatih' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'guzelyurt', display: 'Güzelyurt' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'i̇ncirtepe', display: 'İncirtepe' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'i̇nonu', display: 'İnönü' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'i̇stiklal', display: 'İstiklal' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'mehtercesme', display: 'Mehterçeşme' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'merkez', display: 'Merkez' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'namik_kemal', display: 'Namık Kemal' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'ornek', display: 'Örnek' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'pinar', display: 'Pınar' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'saadetdere', display: 'Saadetdere' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'sanayii', display: 'Sanayii' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'talatpasa', display: 'Talatpaşa' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'yenikent', display: 'Yenikent' },
    { townValue: 'esenyurt', townDisplay: 'Esenyurt', value: 'yesilkent', display: 'Yeşilkent' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'aksemsettin', display: 'Akşemsettin' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'alibeykoy', display: 'Alibeyköy' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'circir', display: 'Çırçır' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'defterdar', display: 'Defterdar' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'dugmeciler', display: 'Düğmeciler' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'emniyettepe', display: 'Emniyettepe' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'esentepe', display: 'Esentepe' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'merkez', display: 'Merkez' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'gokturk', display: 'Göktürk' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'guzeltepe', display: 'Güzeltepe' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'i̇slambey', display: 'İslambey' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'karadolap', display: 'Karadolap' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'mimarsinan', display: 'Mimarsinan' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'mithatpasa', display: 'Mithatpaşa' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'nisanca', display: 'Nişanca' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'rami_cuma', display: 'Rami Cuma' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'rami_yeni', display: 'Rami Yeni' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'sakarya', display: 'Sakarya' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'silahtaraga', display: 'Silahtarağa' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'topcular', display: 'Topçular' },
    { townValue: 'eyup', townDisplay: 'Eyüp', value: 'yesilpinar', display: 'Yeşilpınar' },
    { townValue: 'fatih', townDisplay: 'Fatihh', value: 'aksaray', display: 'Aksaray' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'aksemsettin', display: 'Akşemsettin' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'alemdar', display: 'Alemdar' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'ali_kuscu', display: 'Ali Kuşçu' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'atikali', display: 'Atikali' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'ayvansaray', display: 'Ayvansaray' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'balabanaga', display: 'Balabanağa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'balat', display: 'Balat' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'beyazit', display: 'Beyazıt' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'binbirdirek', display: 'Binbirdirek' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'cankurtaran', display: 'Cankurtaran' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'cerrahpasa', display: 'Cerrahpaşa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'cibali', display: 'Cibali' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'demirtas', display: 'Demirtaş' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'dervis_ali', display: 'Derviş Ali' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'eminsinan', display: 'Eminsinan' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'hacikadin', display: 'Hacıkadın' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'hasekisultan', display: 'Hasekisultan' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'hirkaiserif', display: 'Hırkaişerif' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'hobyar', display: 'Hobyar' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'hoca_giyasettin', display: 'Hoca Giyasettin' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'hocapasa', display: 'Hocapaşa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'i̇skenderpasa', display: 'İskenderpaşa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'kalenderhane', display: 'Kalenderhane' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'karagumruk', display: 'Karagümrük' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'katip_kasim', display: 'Katip Kasım' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'kemalpasa', display: 'Kemalpaşa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'kocamustafapasa', display: 'Kocamustafapaşa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'kucukayasofya', display: 'Küçükayasofya' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mercan', display: 'Mercan' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mesihpasa', display: 'Mesihpaşa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mevlanakapi', display: 'Mevlanakapı' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mimar_hayrettin', display: 'Mimar Hayrettin' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mimar_kemalettin', display: 'Mimar Kemalettin' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mollafenari', display: 'Mollafenari' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mollagurani', display: 'Mollagürani' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'mollahusrev', display: 'Mollahüsrev' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'muhsinehatun', display: 'Muhsinehatun' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'nisanca', display: 'Nişanca' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'rustempasa', display: 'Rüstempaşa' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'saracishak', display: 'Saraçishak' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'saridemir', display: 'Sarıdemir' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'seyyvalue_omer', display: 'Seyyvalue Ömer' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'silivrikapi', display: 'Silivrikapı' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'sultanahmet', display: 'Sultanahmet' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'sururi', display: 'Sururi' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'suleymaniye', display: 'Süleymaniye' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'sumbulefendi', display: 'Sümbülefendi' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'sehremini', display: 'Şehremini' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'sehsuvarbey', display: 'Şehsuvarbey' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'tahtakale', display: 'Tahtakale' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'tayahatun', display: 'Tayahatun' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'topkapi', display: 'Topkapı' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'yavuzsinan', display: 'Yavuzsinan' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'yavuz_sultan_selim', display: 'Yavuz Sultan Selim' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'yedikule', display: 'Yedikule' },
    { townValue: 'fatih', townDisplay: 'Fatih', value: 'zeyrek', display: 'Zeyrek' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'baglarbasi', display: 'Bağlarbaşı' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'barbaros_hayrettin_pasa', display: 'Barbaros Hayrettin Paşa' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'fevzi_cakmak', display: 'Fevzi Çakmak' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'hurriyet', display: 'Hürriyet' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'karadeniz', display: 'Karadeniz' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'karayollari', display: 'Karayolları' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'karlitepe', display: 'Karlıtepe' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'kazim_karabekir', display: 'Kazım Karabekir' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'merkez', display: 'Merkez' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'mevlana', display: 'Mevlana' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'pazarici', display: 'Pazariçi' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'sarigol', display: 'Sarıgöl' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'semsipasa', display: 'Şemsipaşa' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'yenidogan', display: 'Yenidoğan' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'gaziosmanpasa', townDisplay: 'Gaziosmanpaşa', value: 'yildiztabya', display: 'Yıldıztabya' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'akincilar', display: 'Akıncılar' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'abdurrahman_nafiz_gurman', display: 'Abdurrahman Nafiz Gürman' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'gencosman', display: 'Gençosman' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'gunestepe', display: 'Güneştepe' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'guven', display: 'Güven' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'haznedar', display: 'Haznedar' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'maresal_fevzi_cakmak', display: 'Mareşal Fevzi Çakmak' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'mehmet_nezih_ozmen', display: 'Mehmet Nezih Özmen' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'merkez', display: 'Merkez' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'sanayi', display: 'Sanayi' },
    { townValue: 'gungoren', townDisplay: 'Güngören', value: 'tozkoparan', display: 'Tozkoparan' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: '19_mayis', display: '19 Mayıs' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'acibadem', display: 'Acıbadem' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'bostanci', display: 'Bostancı' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'caddebostan', display: 'Caddebostan' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'caferaga', display: 'Caferağa' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'dumlupinar', display: 'Dumlupınar' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'egitim', display: 'Eğitim' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'erenkoy', display: 'Erenköy' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'fenerbahce', display: 'Fenerbahçe' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'feneryolu', display: 'Feneryolu' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'fikirtepe', display: 'Fikirtepe' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'goztepe', display: 'Göztepe' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'hasanpasa', display: 'Hasanpaşa' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'kosuyolu', display: 'Koşuyolu' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'kozyatagi', display: 'Kozyatağı' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'merdivenkoy', display: 'Merdivenköy' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'osmanaga', display: 'Osmanağa' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'rasimpasa', display: 'Rasimpaşa' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'sahrayicedit', display: 'Sahrayıcedit' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'suadiye', display: 'Suadiye' },
    { townValue: 'kadikoy', townDisplay: 'Kadıköy', value: 'zuhtupasa', display: 'Zühtüpaşa' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'caglayan', display: 'Çağlayan' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'celiktepe', display: 'Çeliktepe' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'gultepe', display: 'Gültepe' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'emniyet', display: 'Emniyet' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'gursel', display: 'Gürsel' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'hamidiye', display: 'Hamidiye' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'harmantepe', display: 'Harmantepe' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'hurriyet', display: 'Hürriyet' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'mehmet_akif_ersoy', display: 'Mehmet Akif Ersoy' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'merkez', display: 'Merkez' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'nurtepe', display: 'Nurtepe' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'ortabayir', display: 'Ortabayır' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'sanayi', display: 'Sanayi' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'seyrantepe', display: 'Seyrantepe' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'sirintepe', display: 'Şirintepe' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'talatpasa', display: 'Talatpaşa' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'telsizler', display: 'Telsizler' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'yahya_kemal', display: 'Yahya Kemal' },
    { townValue: 'kagithane', townDisplay: 'Kağıthane', value: 'yesilce', display: 'Yeşilce' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'atalar', display: 'Atalar' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'cevizli', display: 'Cevizli' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'cavusoglu', display: 'Çavuşoğlu' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'esentepe', display: 'Esentepe' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'gumuspinar', display: 'Gümüşpınar' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'hurriyet', display: 'Hürriyet' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'karliktepe', display: 'Karlıktepe' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'kordonboyu', display: 'Kordonboyu' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'orhantepe', display: 'Orhantepe' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'ortamahalle', display: 'Ortamahalle' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'petrol_is', display: 'Petrol-iş' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'soganlik', display: 'Soğanlık' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'topselvi', display: 'Topselvi' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'ugur_mumcu', display: 'Uğur Mumcu' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'yakacik_carsi', display: 'Yakacık Çarşı' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'yakacik_Yeni', display: 'Yakacık Yeni' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'yali', display: 'Yalı' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'yukari', display: 'Yukarı' },
    { townValue: 'kartal', townDisplay: 'Kartal', value: 'yunus', display: 'Yunus' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'atakent', display: 'Atakent' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'ataturk', display: 'Atatürk' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'besyol', display: 'Beşyol' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'cennet', display: 'Cennet' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'fatih', display: 'Fatih' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'fevzi_cakmak', display: 'Fevzi Çakmak' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'gultepe', display: 'Gültepe' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'halkali', display: 'Halkalı' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'i̇nonu', display: 'İnönü' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'i̇stasyon', display: 'İstasyon' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'kanarya', display: 'Kanarya' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'kartaltepe', display: 'Kartaltepe' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'kemalpasa', display: 'Kemalpaşa' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'mehmet_akif', display: 'Mehmet Akif' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'sogutlucesme', display: 'Söğütlüçeşme' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'sultanmurat', display: 'Sultanmurat' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'tevfikbey', display: 'Tevfikbey' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'yarimburgaz', display: 'Yarımburgaz' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'kucukcekmece', townDisplay: 'Küçükçekmece', value: 'yesilova', display: 'Yeşilova' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'altaycesme', display: 'Altayçeşme' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'altintepe', display: 'Altıntepe' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'aydinevler', display: 'Aydınevler' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'baglarbasi', display: 'Bağlarbaşı' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'basibuyuk', display: 'Başıbüyük' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'buyukbakkalkoy', display: 'Büyükbakkalköy' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'cevizli', display: 'Cevizli' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'cinar', display: 'Çınar' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'esenkent', display: 'Esenkent' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'feyzullah', display: 'Feyzullah' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'findikli', display: 'Fındıklı' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'girne', display: 'Girne' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'gulensu', display: 'Gülensu' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'gulsuyu', display: 'Gülsuyu' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'i̇dealtepe', display: 'İdealtepe' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'kucukyali', display: 'Küçükyalı' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'yali', display: 'Yalı' },
    { townValue: 'maltepe', townDisplay: 'Maltepe', value: 'zumrutevler', display: 'Zümrütevler' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'ahmet_yesevi', display: 'Ahmet Yesevi' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'bahcelievler', display: 'Bahçelievler' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'bati', display: 'Batı' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'camcesme', display: 'Çamçeşme' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'camlik', display: 'Çamlık' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'cinardere', display: 'Çınardere' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'dogu', display: 'Doğu' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'dumlupinar', display: 'Dumlupınar' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'ertugrulgazi', display: 'Ertuğrulgazi' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'esenler', display: 'Esenler' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'esenyali', display: 'Esenyalı' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'fatih', display: 'Fatih' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'fevzi_cakmak', display: 'Fevzi Çakmak' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'gullubaglar', display: 'Güllübağlar' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'guzelyali', display: 'Güzelyalı' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'harmandere', display: 'Harmandere' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'kavakpinar', display: 'Kavakpınar' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'kaynarca', display: 'Kaynarca' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'kurtkoy', display: 'Kurtköy' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'orhangazi', display: 'Orhangazi' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'orta', display: 'Orta' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'ramazanoglu', display: 'Ramazanoğlu' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'sanayi', display: 'Sanayi' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'sapanbaglari', display: 'Sapanbağları' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'suluntepe', display: 'Sülüntepe' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'seyhli', display: 'Şeyhli' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'velibaba', display: 'Velibaba' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'yayalar', display: 'Yayalar' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'yenisehir', display: 'Yenişehir' },
    { townValue: 'pendik', townDisplay: 'Pendik', value: 'yesilbaglar', display: 'Yeşilbağlar' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'abdurrahmangazi', display: 'Abdurrahmangazi' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'akpinar', display: 'Akpınar' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'ataturk', display: 'Atatürk' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'emek', display: 'Emek' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'eyupsultan', display: 'Eyüpsultan' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'fatih', display: 'Fatih' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'hilal', display: 'Hilal' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'i̇nonu', display: 'İnönü' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'kemal_turkler', display: 'Kemal Türkler' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'meclis', display: 'Meclis' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'merve', display: 'Merve' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'mevlana', display: 'Mevlana' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'osmangazi', display: 'Osmangazi' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'safa', display: 'Safa' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'sarigazi', display: 'Sarıgazi' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'veysel_karani', display: 'Veysel Karani' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'yenidogan', display: 'Yenidoğan' },
    { townValue: 'sancaktepe', townDisplay: 'Sancaktepe', value: 'yunus_emre', display: 'Yunus Emre' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'ayazaga', display: 'Ayazağa' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'baltalimani', display: 'Baltalimanı' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'bahcekoy_kemer', display: 'Bahçeköy Kemer' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'bahcekoy', display: 'Bahçeköy' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'bahcekoy_yenimahalle', display: 'Bahçeköy Yenimahalle' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'buyukdere', display: 'Büyükdere' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'cayirbasi', display: 'Çayırbaşı' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'camlitepe', display: 'Çamlıtepe' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'darussafaka', display: 'Darüşşafaka' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'demirci', display: 'Demirci' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'derbent_camlitepe', display: 'Derbent (Çamlıtepe)' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'emirgan', display: 'Emirgan' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'fatih_sultan_mehmet', display: 'Fatih Sultan Mehmet' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'ferahevler', display: 'Ferahevler' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'i̇stinye', display: 'İstinye' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'kazim_karabekir', display: 'Kazım Karabekir' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'kirecburnu', display: 'Kireçburnu' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'kocatas', display: 'Kocataş' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'maden', display: 'Maden' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'pinar', display: 'Pınar' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'poligon', display: 'Poligon' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'ptt_evleri', display: 'PTT Evleri' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'resatpasa', display: 'Reşatpaşa' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'rumelihisari', display: 'Rumelihisarı' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'rumelikavagi', display: 'Rumelikavağı' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'maslak', display: 'Maslak' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'merkez', display: 'Merkez' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'tarabya', display: 'Tarabya' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'yenikoy', display: 'Yeniköy' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'yenimahalle', display: 'Yenimahalle' },
    { townValue: 'sariyer', townDisplay: 'Sarıyer', value: 'zekeriyakoy', display: 'Zekeriyaköy' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'akoren', display: 'Akören' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'alibey', display: 'Alibey' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'alipasa_yapagca', display: 'Alipaşa (Yapağca)' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'buyuk_cavuslu', display: 'Büyük Çavuşlu' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'canta_fatih', display: 'Çanta Fatih' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'canta_mimarsinan', display: 'Çanta Mimarsinan' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'degirmenkoy_ismetpasa', display: 'Değirmenköy İsmetpaşa' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'degirmenkoy_fevzipasa', display: 'Değirmenköy Fevzipaşa' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'fatih', display: 'Fatih' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'fener', display: 'Fener' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'gazitepe', display: 'Gazitepe' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'gumusyaka', display: 'Gümüşyaka' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'kadikoy', display: 'Kadıköy' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'kavakli_hurriyet', display: 'Kavaklı Hürriyet' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'kavakli_cumhuriyet', display: 'Kavaklı Cumhuriyet' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'kucuk_kilicli', display: 'Küçük Kılıçlı' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'mimarsinan', display: 'Mimarsinan' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'ortakoy', display: 'Ortaköy' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'piri_mehmet_pasa', display: 'Piri Mehmet Paşa' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'selimpasa', display: 'Selimpaşa' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'semizkumlar', display: 'Semizkumlar' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'yeni_mahalle', display: 'Yeni Mahalle' },
    { townValue: 'silivri', townDisplay: 'Silivri', value: 'yolcati', display: 'Yolçatı' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'abdurrahmangazi', display: 'Abdurrahmangazi' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'adil', display: 'Adil' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'ahmet_yesevi', display: 'Ahmet Yesevi' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'aksemsettin', display: 'Akşemsettin' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'battalgazi', display: 'Battalgazi' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'fatih', display: 'Fatih' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'hamidiye', display: 'Hamidiye' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'hasanpasa', display: 'Hasanpaşa' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'mecidiye', display: 'Mecidiye' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'mehmet_akif', display: 'Mehmet Akif' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'mimarsinan', display: 'Mimarsinan' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'necip_fazil', display: 'Necip Fazıl' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'orhangazi', display: 'Orhangazi' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'turgutreis', display: 'Turgutreis' },
    { townValue: 'sultanbeyli', townDisplay: 'Sultanbeyli', value: 'yavuz_selim', display: 'Yavuz Selim' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: '50_yil', display: '50. yıl' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: '75_yil', display: '75. yıl' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'cebeci', display: 'Cebeci' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'esentepe', display: 'Esentepe' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'eski_habibler', display: 'Eski Habibler' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'gazi', display: 'Gazi' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'habibler', display: 'Habibler' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'i̇smetpasa', display: 'İsmetpaşa' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'malkocoglu', display: 'Malkoçoğlu' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'sultanciftligi', display: 'Sultançiftliği' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'ugur_mumcu', display: 'Uğur Mumcu' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'yayla', display: 'Yayla' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'yunusemre', display: 'Yunusemre' },
    { townValue: 'sultangazi', townDisplay: 'Sultangazi', value: 'zubeydehanim', display: 'Zübeydehanım' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'agva', display: 'Ağva' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'ahmetli', display: 'Ahmetli' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'alacali', display: 'Alacalı' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'balibey', display: 'Balibey' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'cavus', display: 'Çavuş' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'cayirbasi', display: 'Çayırbaşı' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'dogancili', display: 'Doğancılı' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'hacikasim', display: 'Hacıkasım' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'imrendere', display: 'İmrendere' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'imrendi', display: 'İmrendi' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'kumbaba', display: 'Kumbaba' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'mesrutiyet', display: 'Meşrutiyet' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'sahilkoy', display: 'Sahilköy' },
    { townValue: 'sile', townDisplay: 'Şile', value: 'suayipli', display: 'Şuayipli' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: '19_mayis', display: '19 Mayıs' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'bozkurt', display: 'Bozkurt' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'duatepe', display: 'Duatepe' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'ergenekon', display: 'Ergenekon' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'esentepe', display: 'Esentepe' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'eskisehir', display: 'Eskişehir' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'ferikoy', display: 'Feriköy' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'fulya', display: 'Fulya' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'gulbahar', display: 'Gülbahar' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'halaskargazi', display: 'Halaskargazi' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'halide_edip_adivar', display: 'Halide Edip Adıvar' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'halil_rifat_pasa', display: 'Halil Rıfat Paşa' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'harbiye', display: 'Harbiye' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'huzur', display: 'Huzur' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'i̇nonu', display: 'İnönü' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'i̇zztpasa', display: 'İzztpaşa' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'kaptanpasa', display: 'Kaptanpaşa' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'kustepe', display: 'Kuştepe' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'mahmut_sevket_pasa', display: 'Mahmut Şevket Paşa' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'mecidiyekoy', display: 'Mecidiyeköy' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'merkez', display: 'Merkez' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'mesrutiyet', display: 'Meşrutiyet' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'pasa', display: 'Paşa' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'tesvikiye', display: 'Teşvikiye' },
    { townValue: 'sisli', townDisplay: 'Şişli', value: 'yayla', display: 'Yayla' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'anadolu', display: 'Anadolu' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'aydinli', display: 'Aydınlı' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'aydintepe', display: 'Aydıntepe' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'cami', display: 'Cami' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'evliya_celebi', display: 'Evliya Çelebi' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'fatih', display: 'Fatih' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'firat', display: 'Fırat' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'i̇cmeler', display: 'İçmeler' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'i̇stasyon', display: 'İstasyon' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'mescit', display: 'Mescit' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'mimarsinan', display: 'Mimarsinan' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'orhanli', display: 'Orhanlı' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'orta', display: 'Orta' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'postane', display: 'Postane' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'sifa', display: 'Şifa' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'tepeoren', display: 'Tepeören' },
    { townValue: 'tuzla', townDisplay: 'Tuzla', value: 'yayla', display: 'Yayla' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'adem_yavuz', display: 'Adem Yavuz' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'altinsehir', display: 'Altınşehir' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'armaganevler', display: 'Armağanevler' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'asagidudullu', display: 'Aşağıdudullu' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'atakent', display: 'Atakent' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'ataturk', display: 'Atatürk' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'cemil_meric', display: 'Cemil Meriç' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'cakmak', display: 'Çakmak' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'camlik', display: 'Çamlık' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'dumlupinar', display: 'Dumlupınar' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'elmalikent', display: 'Elmalıkent' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'esenevler', display: 'Esenevler' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'esensehir', display: 'Esenşehir' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'fatih_sultan_mehmet', display: 'Fatih Sultan Mehmet' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'hekimbasi', display: 'Hekimbaşı' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'huzur', display: 'Huzur' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'ihlamurkuyu', display: 'Ihlamurkuyu' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'i̇nkilap', display: 'İnkılap' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'i̇stiklal', display: 'İstiklal' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'kazim_karabekir', display: 'Kazım Karabekir' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'mehmet_akif', display: 'Mehmet Akif' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'madenler', display: 'Madenler' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'namik_kemal', display: 'Namık Kemal' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'necip_fazil', display: 'Necip Fazıl' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'parseller', display: 'Parseller' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'saray', display: 'Saray' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'site', display: 'Site' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'serifali', display: 'Şerifali' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'tantavi', display: 'Tantavi' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'tatlisu', display: 'Tatlısu' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'tepeustu', display: 'Tepeüstü' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'topagaci', display: 'Topağacı' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'yamanevler', display: 'Yamanevler' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'yeni_sanayi', display: 'Yeni Sanayi' },
    { townValue: 'umraniye', townDisplay: 'Ümraniye', value: 'yukaridudullu', display: 'Yukarıdudullu' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'acibadem', display: 'Acıbadem' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'ahmediye', display: 'Ahmediye' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'altunizade', display: 'Altunizade' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'aziz_mahmud_hudayi', display: 'Aziz Mahmud Hüdayi' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'bahcelievler', display: 'Bahçelievler' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'barbaros', display: 'Barbaros' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'beylerbeyi', display: 'Beylerbeyi' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'bulgurlu', display: 'Bulgurlu' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'burhaniye', display: 'Burhaniye' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'cumhuriyet', display: 'Cumhuriyet' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'cengelkoy', display: 'Çengelköy' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'ferah', display: 'Ferah' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'guzeltepe', display: 'Güzeltepe' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'i̇cadiye', display: 'İcadiye' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kandilli', display: 'Kandilli' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kirazlitepe', display: 'Kirazlıtepe' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kisikli', display: 'Kısıklı' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kuleli', display: 'Kuleli' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kuzguncuk', display: 'Kuzguncuk' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kucuk_camlica', display: 'Küçük Çamlıca' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kucuksu', display: 'Küçüksu' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'kupluce', display: 'Küplüce' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'mehmet_akif_ersoy', display: 'Mehmet Akif Ersoy' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'mimar_sinan', display: 'Mimar Sinan' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'murat_reis', display: 'Murat Reis' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'salacak', display: 'Salacak' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'selami_ali', display: 'Selami Ali' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'selimiye', display: 'Selimiye' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'sultantepe', display: 'Sultantepe' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'unalan', display: 'Ünalan' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'valide_i_atik', display: 'Valide-i Atik' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'yavuzturk', display: 'Yavuztürk' },
    { townValue: 'uskudar', townDisplay: 'Üsküdar', value: 'zeynep_kamil', display: 'Zeynep Kamil' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'bestelsiz', display: 'Beştelsiz' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'cirpici', display: 'Çırpıcı' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'gokalp', display: 'Gökalp' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'kazlicesme', display: 'Kazlıçeşme' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'maltepe', display: 'Maltepe' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'merkezefendi', display: 'Merkezefendi' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'nuripasa', display: 'Nuripaşa' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'seyitnizam', display: 'Seyitnizam' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'sumer', display: 'Sümer' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'telsiz', display: 'Telsiz' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'veliefendi', display: 'Veliefendi' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'yenvalueogan', display: 'Yenvalueoğan' },
    { townValue: 'zeytinburnu', townDisplay: 'Zeytinburnu', value: 'yesiltepe', display: 'Yeşiltepe' }

];

ilceler[] = [

    { value: 'adalar', display: 'Adalar' },
    { value: 'arnavutkoy', display: 'Arnavutköy' },
    { value: 'atasehir', display: 'Atasehir' },
    { value: 'avcilar', display: 'Avcılar' },
    { value: 'bagcilar', display: 'Bağcılar' },
    { value: 'bahcelievler', display: 'Bahçelievler' },
    { value: 'bakirkoy', display: 'Bakırköy' },
    { value: 'basaksehir', display: 'Başakşehir' },
    { value: 'bayrampasa', display: 'Bayrampaşa' },
    { value: 'besiktas', display: 'Beşiktaş' },
    { value: 'beykoz', display: 'Beykoz' },
    { value: 'beylikduzu', display: 'Beylikdüzü' },
    { value: 'beyoglu', display: 'Beyoğlu' },
    { value: 'buyukcekmece', display: 'Büyükçekmece' },
    { value: 'catalca', display: 'Çatalca' },
    { value: 'cekmekoy', display: 'Çekmeköy' },
    { value: 'esenler', display: 'Esenler' },
    { value: 'esenyurt', display: 'Esenyurt' },
    { value: 'eyup', display: 'Eyüp' },
    { value: 'fatih', display: 'Fatih' },
    { value: 'gaziosmanpasa', display: 'Gaziosmanpaşa' },
    { value: 'gungoren', display: 'Güngören' },
    { value: 'kadikoy', display: 'Kadıköy' },
    { value: 'kagithane', display: 'Kağıthane' },
    { value: 'kartal', display: 'Kartal' },
    { value: 'kucukcekmece', display: 'Küçükçekmece' },
    { value: 'maltepe', display: 'Maltepe' },
    { value: 'pendik', display: 'Pendik' },
    { value: 'sancaktepe', display: 'Sancaktepe' },
    { value: 'sariyer', display: 'Sarıyer' },
    { value: 'silivri', display: 'Silivri' },
    { value: 'sultanbeyli', display: 'Sultanbeyli' },
    { value: 'sultangazi', display: 'Sultangazi' },
    { value: 'sile', display: 'Şile' },
    { value: 'sisli', display: 'Şişli' },
    { value: 'tuzla', display: 'Tuzla' },
    { value: 'umraniye', display: 'Ümraniye' },
    { value: 'uskudar', display: 'Üsküdar' },
    { value: 'zeytinburnu', display: 'Zeytinburnu' }

];
